services:
  api_gateway:
    build:
      context: ./http-api-gateway
      dockerfile: Dockerfile
    command: npm run start:dev
    volumes:
      - ./http-api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    restart: unless-stopped

  users_microservice:
    build:
      context: ./users-microservice
      dockerfile: Dockerfile
    command: npm run start:dev
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - postgres
    volumes:
      - ./users-microservice:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  payments_microservice:
    build:
      context: ./payments-microservice
      dockerfile: Dockerfile
    command: npm run start:dev
    volumes:
      - ./payments-microservice:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  auth_microservice:
    build:
      context: ./auth-microservice
      dockerfile: Dockerfile
    command: npm run start:dev
    volumes:
      - ./auth-microservice:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  nats:
    image: nats
    ports:
      - 4222:4222

  # 1 Postgres (Permanent Data)
  postgres:
    image: postgres:15
    container_name: db_user
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Redis (Cache)
  redis:
    image: redis:7-alpine
    container_name: cache_instance
    restart: always
    ports:
      - "6379:6379"

  products_microservice:
    build:
      context: ./products-microservice
      dockerfile: Dockerfile
    command: npm run start:dev
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - postgres
    volumes:
      - ./products-microservice:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  inventory_microservice:
    build:
      context: ./inventory-microservice
      dockerfile: Dockerfile
    command: npm run start:dev
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - postgres
    volumes:
      - ./inventory-microservice:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  sales_microservice:
    build:
      context: ./sales-microservice
      dockerfile: Dockerfile
    command: npm run start:dev
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - postgres
    volumes:
      - ./sales-microservice:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

volumes:
  postgres_data: